### ISSUE TITLE
After `delete` interaction, follow up modifications fail until frame is changed back and forth

### ISSUE THREAD

**Issue by RokasEl** [zincware/ZnDraw#280] opened 2023-11-20 17:50 UTC
This error message is raised:
```
Traceback (most recent call last):
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/socketio/client.py", line 705, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/socketio/client.py", line 581, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/socketio/client.py", line 629, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/zndraw/zndraw.py", line 373, in modifier_run
    modifier.run(self)
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/zndraw/modify/__init__.py", line 321, in run
    self.method.run(vis)
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/moldiff_zndraw/main.py", line 234, in run
    self.run_type.run(
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/moldiff_zndraw/main.py", line 88, in run
    if len(vis.atoms):
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/zndraw/zndraw.py", line 173, in atoms
    return self[self.step]
  File "/home/rokas/miniconda3/envs/genesis/lib/python3.10/site-packages/zndraw/zndraw.py", line 154, in __getitem__
    data = atoms_list[0] if is_scalar else atoms_list
```

**Comment by PythonFZ** [comment] 2024-01-21 10:33
Should be fixed in main - issue was caused by the step being larger than what is available.

**Closed by PythonFZ** 2024-01-21 10:33 UTC
